### ISSUE TITLE
rake spec:javascript when RAILS_ENV is not test

### ISSUE THREAD

**Issue by shlima** [searls/jasmine-rails#121]
Hello. When I run `rake spec:javascript ` with `RAILS_ENV` different than `test` I get:

```shell
Finished
-----------------
0 specs, 0 failures in 0.002s.
```

(there are several specs presents, but nothing are running)

**Comment by christiannelson** [comment]
FWIW, this is how rspec handles running specs in test mode even though rake itself is invoked in development mode:

https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/tasks/rspec.rake#L23

**Comment by searls** [comment]
@christiannelson if they're accomplishing it, I'd be surprised if that is what's doing it under Rails 4.x. As I see it, the problem is that right there in the generated `Rakefile` of Rails 4 is basically `Rails.application.load_tasks`, which will instantiate the application in, by default "development". Any rake task changing the value of RACK_ENV/RAILS_ENV will then have no effect because the app will have been instantiated.

**Comment by henrik** [comment]
Just happened across [this](http://blog.testdouble.com/posts/2015-02-16-arcane-knowledge.html):

> If you don't add `require "rails/test_unit/railtie"` to your application.rb, then the server started by rake test will actually be initialized in development mode, even if your test helper explicitly sets ENV['RAILS_ENV'] = "test" (further blurring the line between production-scope and test-scope dependencies)

Maybe something like that could work for jasmine-rails as well. Sucks to ask the user to add something to application.rb, or do it automatically for them, but maybe less than having to specify the ENV every time? Assuming it works.

**Comment by searls** [comment]
Hahah, I bet you're write. Funny I didn't connect the dots here and it actually took you to quote me at myself (within the same week) to make the point

**Comment by henrik** [comment]
Haha, oh yeah, that was you. Well then :D

**Comment by searls** [comment]
@henrik did you try adding the test unit railtie to your application? Does that resolve it?

**Comment by henrik** [comment]
Haven't tried. Might do tomorrow at work.

**Comment by jurglic** [comment]
I have the issue with tests running twice in the test environment. I've tried every possible way of setting it to test, in env variable, inside rake task, etc... always tests run twice. 

I'm using jasmine-rails 0.10.7 and rails 4.0.13. Any ideas what to do?

**Comment by searls** [comment]
@jurglic you sure this happens even when you set the env via the shell? e.g. `RAILS_ENV=test rake...`?

**Comment by jurglic** [comment]
@searls Yes, I use this command `RAILS_ENV=test rake spec:javascript`.

**Comment by shlima** [comment]
@jurglic there is an working alternative: https://github.com/jasmine/jasmine-gem

**Comment by jurglic** [comment]
@searls I've thought about it but it doesn't seem to support rails' asset pipeline. Actually we were using jasminerice on Rails 3, but now upgrading to Rails 4 it doesn't work so I the next best option seemed jasmine-rails. Are you suggesting we should reconsider using the jasmine-gem for the long-term?

**Comment by rudyjahchan** [comment]
@searls @christiannelson Going back to how RSpec gets away with setting the environment variable (https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/tasks/rspec.rake#L23) under Rails 4, it works because the RSpec Rails tasks then do a `system` call out to the `rspec` command, where the Rails application will be loaded by the `rails_helper` in the correct environment.

Which may point to a possible solution; add an executable that invokes the runner. Then the rake task will launch the executable, passing in the commands. Anything I'm missing? If not, I can take a crack at it.

**Comment by searls** [comment]
I'm not sure you even need the additional executable, do you? You could just add guard close that, instead of executing further, will shell out to `RAILS_ENV=test bundle exec rake spec:javascripts` in the event that `Rails.env.test?` fails. No?

In either case, please by all means go for it @rudyjahchan

**Comment by rudyjahchan** [comment]
As an update, I got it working both as a guard clause and a runner script. Here's it "in flight" as a script: https://github.com/searls/jasmine-rails/compare/master...rudyjahchan:issue/ensure-rails-env-test-121

Personally prefer the script approach as it allows some environment flexibility (you can actually pass a different environment than `test` to the `jasmine-rails` script).

I have three outstanding issues though I would love guidance on:

* I can't seem to get the tests to run, even before my changes! I went ahead with the implementation to validate the idea but it makes me nervous.
* As you can see in the script (https://github.com/rudyjahchan/jasmine-rails/blob/issue/ensure-rails-env-test-121/bin/jasmine-rails#L5), it loads the Rails environment by assuming `config/environment.rb` is off of the current working directory. It worked in practice, but I am wondering is there a better way? RSpec gets around this because the `rails_helper` in a project does this for you.
* Finally, this is my first time introducing a binary into a gem (fine, that's my other reasons for taking this approach ;-)), and when I build and install the gem directly, the binary is successful installed. However, if I try to set up the `Gemfile` to get the gem by path or via git, it never installs the binary. rakkafrakka.

Cheers!

**Comment by searls** [comment]
Hey @rudyjahchan I haven't reviewed your approach yet but the tests should now pass under Ruby 2.0.x.

I personally still prefer the short-circuit fork in rake to a bin script, because I don't want to even support running tests in development or production.

**Comment by rudyjahchan** [comment]
@searls PR submitted (as you can see). Went with the short-circuit to get this in, and will submit the separate script as a different PR another day.

**Comment by shepmaster** [comment]
In our case, we were able to run our tests for over a year in the `development` environment without a problem. Only recently did we hit issues where JS assets started getting included twice, overriding each other. Perhaps it would make sense to check the environment and produce a warning (or fail?) if it's not correct?

**Comment by searls** [comment]
+1 would love to see that PR, or one that forked in the event it was not set to test

**Comment by searls** [comment]
This should finally be fixed as of 0.12.0

**Comment by henrik** [comment]
@searls Oh, awesome :) Glad to see this finally resolved.
